spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_shopping_app?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  
  #SMTP configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${email.pwd}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            
application:
 jwt:
  secrete: ${jwt.secrete}
  access_expiry_seconds: 3600
  refresh_expiry_seconds: 1296000
 cookie:
  domain: localhost
  same_site: Lax
  secure: false